/gate/world/daughters/name          phantom
/gate/world/daughters/insert        box
/gate/phantom/geometry/setXLength   10.0 cm
/gate/phantom/geometry/setYLength   10.0 cm
/gate/phantom/geometry/setZLength   10.0 cm
/gate/phantom/setMaterial           Vacuum

/gate/phantom/placement/setTranslation              0.0 0.0 0.0 mm
/gate/phantom/placement/setRotationAxis             1 0 0
/gate/phantom/placement/setRotationAngle            0 deg

/gate/phantom/vis/setColor          red