/gate/actor/addActor    PhaseSpaceActor         gamma_birth
/gate/actor/gamma_birth/save                    output/PhaseSpace.root
/gate/actor/gamma_birth/attachTo                phantom

/gate/actor/gamma_birth/enableEkine              false
/gate/actor/gamma_birth/enableXPosition          true
/gate/actor/gamma_birth/enableYPosition          true
/gate/actor/gamma_birth/enableZPosition          true
/gate/actor/gamma_birth/enableXDirection         false
/gate/actor/gamma_birth/enableYDirection         false
/gate/actor/gamma_birth/enableZDirection         false
/gate/actor/gamma_birth/enableProductionVolume   false
/gate/actor/gamma_birth/enableProductionProcess  true
/gate/actor/gamma_birth/enableParticleName       true
/gate/actor/gamma_birth/enableWeight             false
/gate/actor/gamma_birth/enableTrackLength        false

/gate/actor/gamma_birth/storeSecondaries         true
#/gate/actor/MyActor/useVolumeFrame